### ISSUE TITLE
trajectory_tracker: angle_remain is not properly normalized

### ISSUE THREAD

**Issue by at-wat** [at-wat/neonavigation#246]
after https://github.com/at-wat/neonavigation/pull/239, `angle_remain` is normalized between 0:2pi which should be -pi:pi

**Comment by at-wat** [comment]
status output:
```yaml
header: 
  seq: 30115
  stamp: 
    secs: 1544582618
    nsecs: 642091600
  frame_id: ''
distance_remains: 0.0
angle_remains: 5.76035785675
status: 2
---
```
