### ISSUE TITLE
Time for path found too long

### ISSUE THREAD

**Issue by HappySamuel** [at-wat/neonavigation#507]
Hi

I am facing issue with the path found taking too long time. This cause the robot to move, stop, move, stop, move until reaching the goal. It's due to the robot already reached the temp goal, while the next path hasn't ready. Need your advice on how can i make the robot to not behave like that? Below are the parameters that i used:

```
costmap_3d:
  ang_resolution: 16
  linear_expand: 0.08 #The lower the value, the faster the map loaded
  linear_spread: 0.5 #0.3 #The lower the value, the faster the map loaded

planner_3d:
  num_threads: 12 #The more the threads, the faster the path planned
  freq: 10.0
  freq_min: 1.0 #0.1
  local_range: 5.0 #The longer the range, the slower the path planned
  find_best: true #false
  min_curve_raduis: 0.0 #0.1
  tolerance_range: 0.1
  tolerance_angle: 0.1
  goal_tolerance_lin: 0.2
  goal_tolerance_ang: 0.2
  goal_tolerance_ang_finish: 0.1 #0.05
  esc_range: 0.25
  fast_map_update: true
  remember_updates: true #false # What's this for????
  jump_detect_frame: base_link
  print_planning_duration: true #false
```
