### ISSUE TITLE
Goal not accepted with real robot

### ISSUE THREAD

**Issue by FrGe2016** [at-wat/neonavigation#632]
Hi great package

The robot is working perfectly when i use the normal navigation stack

I have modified the neonavigation demo.launch file to test it with my linorobot and nothing is planned. Here are the info. 

```
[ERROR] [1639844616.742719628]: Goal [map] pose must be in the map frame [].
```

But the goal pose in in the map frame

```
rostopic echo /move_base_simple/goal
header: 
  seq: 0
  stamp: 
    secs: 1639843216
    nsecs: 753899602
  frame_id: **"map"**
pose: 
  position: 
    x: 8.681979179382324
    y: 3.8665976524353027
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: -0.9830096719102385
    w: 0.18355376577702048
---
```

My launch file for my physical linorobot is : attached
[physical_demo.launch.txt](https://github.com/at-wat/neonavigation/files/7739587/physical_demo.launch.txt)
